# Generated by Django 4.0.2 on 2022-02-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='main',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='main',
            name='city',
        ),
        migrations.RemoveField(
            model_name='main',
            name='password2',
        ),
    ]
